export default {
  INIT_CARS: "INIT_CARS",
  CREATE_CAR: "CREATE_CAR",
  UPDATE_CAR: "UPDATE_CAR",
  DELETE_CAR: "DELETE_CAR",
  DELETE_CAR_FROM_COMPARE_LIST: "DELETE_CAR_FROM_COMPARE_LIST",
  ADD_CAR_TO_COMPARE_LIST: "ADD_CAR_TO_COMPARE_LIST",
};
